### PR TITLE
missing migration file

### PR DESCRIPTION
**Pull request by heydanhey**
@paulyk1983 Hey Paul, here's the missing migration file.

If you have a chance, why don't you pull this branch down before you merge it and see it you can run the migration and thus hopefully be able to submit a form.

### CODE REVIEW

**Comment by paulyk1983** [comment]
@heydanhey So I pulled the branch down and am still having some issues but not the same ones. I am working through some of them now. Maybe I will have this resolved by the time we meet up tonight.

**Comment by paulyk1983** [comment]
@heydanhey So the only issue for me was line 6 in the rfps controller. 

I had: user_loi_status = user_loi.status

It should be: user_loi_status = user_has_loi.status

Let me know if you still want me to merge this branch.

**Comment by heydanhey** [comment]
@paulyk1983 I noticed the same bug re: `user_has_loi.status`. That's on me because I reviewed Aaron PR and missed the error. I'll have him edit it tonight.

Were you able to rake and submit a form?

**Comment by paulyk1983** [comment]
yup

**Pull request merged**
